# Generated by Django 3.2.7 on 2021-09-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('pub_id', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
